### ISSUE TITLE
Make extension v11-compatible

### ISSUE THREAD

**Issue by adittmar** [bitmotion/auth0-for-typo3#15]
Hello there

right now the TER states that the extension is currently only available for TYPO3 v10. Are there any plans to make this extension v11-compatible as well in the near feature?

Thank you very much and kind regards
Andre

**Comment by elbebass** [comment]
Hi there,

there will be a TYPO3 v11 compatible version. We are working on a complete rewrite. As soon as the basic TYPO3 backend login is possible we plan to release an alpha version.

**Comment by adittmar** [comment]
Hi!

Thanks for the quick response! I do not want to rush but do you have a rough time schedule till when the alpha might be available? Would be great to know for further planning.

Many thanks and I appreciate your efforts with the extension!
Have a great day!

Regards
Andre

**Comment by elbebass** [comment]
Sorry for the late feedback.

For simple backend functionality you can check out the current master @ https://github.com/elbebass/auth0-for-typo3
We started with internal testing today. Most of the times we use auth0 to enable backend admin access for all our employees on all active customer installations.

**Comment by adittmar** [comment]
Hi there
Thank you very much. In the meantime our client is tending to rather use their Azure via SAML since they would like this as their prefered way to handle SSO etc. Perhaps for another project, I will gladly use your extension. In the meantime all the best to get the extension finally into V11 :-)

Regards
Andre

**Comment by elbebass** [comment]
Thanks :)
