### ISSUE TITLE
CallbackMiddleware.php tries to access the TSFE before its initialization

### ISSUE THREAD

**Issue by maximeMckayTurgeon** [bitmotion/auth0-for-typo3#31]
TYPO3: 11.5.31
leuchtfeuer/auth0-for-typo3: 4.0.0

When Bitmotion\Auth0\Middleware\CallbackMiddleware.php tries to instantiate Bitmotion\Auth0\Utility\TokenUtility.php on line 62, 
Bitmotion\Auth0\Utility\TokenUtility->setIssuer() is called, and it tries to access $GLOBALS['TSFE'] before it is initialized, throwing a TYPO3\CMS\Core\Error\Exception.

**Comment by yabid21** [comment]
We have fixed in the version 4.0.1
Note: The frontend login is not yet supported in version 4.0.0 and 4.0.1.

**Comment by maximeMckayTurgeon** [comment]
@yabid21  Do you have a timeframe for frontend login support?
