### ISSUE TITLE
CleanUpCommand bug

### ISSUE THREAD

**Issue by eXahostCOM** [bitmotion/auth0-for-typo3#38]
**Describe the bug**
The function execute in command CleanUpCommand needs an int return value (use symfony self::FAILURE and self::SUCCESS).

**To Reproduce**
1. Install the extension via composer
2. try to execute command or simply try to clear typo3 cache

**Expected behavior**
Please fix this bug :)

**Comment by flossels** [comment]
Some more information on this:

`PHP Fatal error:  Declaration of Leuchtfeuer\Auth0\Command\CleanUpCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in xxx/vendor/leuchtfeuer/auth0/Classes/Command/CleanUpCommand.php on line 70
`

TYPO3: v12.4.14
symfony/console: v7.0.6
