### ISSUE TITLE
Application data record

### ISSUE THREAD

**Issue by 0x0ff** [bitmotion/auth0-for-typo3#6]
Hi,

I'm new to Typo3 and Auth0 and I'm struggling to find and setup the "Application data record".

I've installed the extension from the WebGUI manager.

I can find the Auth0 login object but it seems there is no "Application data record" available... :(

It's probably trivial, can you give me a hint ?

Best regards

**Comment by flossels** [comment]
Hi, which version of this extension do you use?
Since version 3.3 there is a dedicated backend module for configuring Applications available. In prior versions you have to use the "default" way via TYPO3s list module.

**Comment by 0x0ff** [comment]
Hello,

I found out. The record must be created in a folder... As I said, I'm a noob sorry. :(

Thanks for your reply,
