### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\get_message_body_summary()

### ISSUE THREAD

**Issue by stephan-strate** [bitmotion/auth0-for-typo3#7]
**Describe the bug**
Just started to play around with the extension. Installed the extension in version 3.3.1 using the extension manager (version 3.3.2 not available there?) and tried version 3.3.2 manually using composer.
Created the application data record and the login/logout form for frontend. After approving the application on the auth0 site, the error `Call to undefined function GuzzleHttp\Psr7\get_message_body_summary()` appears on the extension side.

**To Reproduce**
1. Login using auth0 frontend plugin
2. Approve the selected application
3. Redirected to your site again

**Expected behavior**
Being logged in without any exception.

Typo3 version: 9.5.0

**Comment by flossels** [comment]
Hi Stephan,

thanks for using this extension and your hint regarding the release.
Since your issue is a "guzzle" issue and is not related to this extension in first place, please see: https://github.com/guzzle/guzzle/issues/2740

**Comment by stephan-strate** [comment]
Thanks for your quick response. This is a guzzle problem, yes. But the extension is broken due to that issue. How do you setup the extension so that it works like intended?

**Comment by flossels** [comment]
The issue should be fixed in newer versions of GuzzleHttp/Psr7 as described in https://github.com/guzzle/guzzle/issues/2740#issuecomment-668131992. Have you already tried to update the package?

**Comment by stephan-strate** [comment]
The guzzlehttp dependency is part of the auth0/auth0-php package. I hit `composer update` for the libraries of this package, no change. The GuzzleHttp/Psr7 is at version 1.7.0 already (according to github the newest one).

**Comment by stephan-strate** [comment]
I can not reproduce this issue again. I reinstalled my whole typo3 instance and now the error is gone.
However. Now another error is occurring: `Mon, 30 Nov 2020 16:05:51 +0100 [ERROR] request="104a3139a6076" component="Bitmotion.Auth0.Utility.Database.UpdateUtility": 1531381794: No settings found. TypoScript included?`
I included the auth0 typoscript as static in main template. The yaml configuration is available under `typo3conf/auth0/config.yaml`.

The error occurs when I try to login. The frontend user is created successfully, but I am not logged in after the redirect from auth0. Do you have any suggestion on how to proceed?
